### PR TITLE
Fix rename new app

### PR DESCRIPTION
**Pull request by simonardejr**
Fix for [#281](https://github.com/laravel-zero/laravel-zero/issues/281#issue-584672031).

### CODE REVIEW

**Comment by nunomaduro** [comment]
Maybe can you make a pull request to remove https://github.com/laravel-zero/laravel-zero/blob/c53013c6015a8677b0419de053e3bb1cb4f0e75f/composer.json#L41 too?

Did you try out this installer with this change?

Thanks!

**Comment by simonardejr** [comment]
I've tried the installer without removing "post-create-project-cmd" and, although it still echo out "Aborted" after first call of "@php application:rename" because of post create command, the command run successfully after.

I've made a commit as you suggested and made a PR removing "post-create-project-cmd" :grinning:

Thanks!

**Review by dbpolito — APPROVED** [review]

**Comment by insign** [comment]
Sorry for this comment might be irrelevant but... is this too serious to get months without a fix?

I just started to try this project that looks very promising and very well documented.

But for now I'm confused. Is this hard to fix or just need some attention?

**Comment by owenvoke** [comment]
We've removed the script that caused the original error. So this PR should now be fine. 👍🏻

We were planning on deprecating the installer and just using:

```bash
composer create-project --prefer-dist --ask laravel-zero/laravel-zero
```

But I think I'd like to update it and I'll merge this to resolve the issue. 👍🏻

**Pull request merged**
