### PR TITLE
Update to use Laravel Zero 7

### PR DESCRIPTION
**Pull request by owenvoke**
Need to do a build of the installer as well using PHP 7.2 👍

### CODE REVIEW

**Review by nunomaduro — CHANGES_REQUESTED** [review]
All is good, you don't build a new binary?

**Comment by owenvoke** [comment]
I'm having issues building one at the moment, I think this may be because the framework is a development dependency and it gets stripped by Box' `exclude-dev-files` directive.

---

Right, I've released the binary with version `v2.4.0` 👍

**Comment by nunomaduro** [comment]
@owenvoke normally the https://github.com/laravel-zero/installer/blob/21ba78c6ea17c02db44a3bc9cbaf23c0ce30f7af/box.json#L12 exclude do *not* exclude the dev dependencies.

**Comment by owenvoke** [comment]
The default seems to be to remove dev files, as far as I can tell this is irrespective of the Composer exclude value. 🤨
https://github.com/humbug/box/blob/master/doc/configuration.md#excluding-dev-files-exclude-dev-files

**Comment by nunomaduro** [comment]
The build you made its working? It haves 755 permissions?

**Comment by owenvoke** [comment]
It appears to be working fine. (I was thinking, it might be good to add some sort of CI to this repository that tests it?)

And yes, it is executable with 755 permissions. :+1:

**Comment by nunomaduro** [comment]
Thanks buddy! I think you can tag a new **minor** version.

**Comment by owenvoke** [comment]
I will tag this in the morning if that's ok? Cheers.

**Comment by nunomaduro** [comment]
Of course,

**Comment by owenvoke** [comment]
Tagged v2.4.0 🎉

**Pull request merged**
